### ISSUE TITLE
Feature Request: use `working-directory`

### ISSUE THREAD

**Issue by mklaber** [nyaayaya/package-version#9]
Rather than falling back on [`env.GITHUB_WORKSPACE`](https://github.com/nyaa8/package-version/blob/master/src/main.ts#L7), it'd be helpful (particularly in mono-repo environments) if `working-directory` were respected.

```yml
name: Bump and Tag Versions

on:
  workflow_dispatch:
    inputs:
      container:
        description: Which container to bump
        required: true

jobs:
jobs:
  bump-and-tag:
    name: Bump ${{ github.event.inputs.container }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./containers/${{ github.event.inputs.container }}
    steps:
      - uses: actions/checkout@v2
      - name: Build Node.js v12.16.3
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.3
      - name: Install
        run: |
          make install-ci
      - name: Bump versions
        run: |
          make release
      - name: Get new version
        id: get_new_version
        uses: nyaa8/package-version@v1.0.3
```

Where `nyaa8/package-version` would look in `./containers/${{ github.event.inputs.container }}` for `package.json`
